name: Auto Push 
on:
  workflow_dispatch:
    inputs:
      test_list:
        description: Only run tests that match the regular expression
        default: ""
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Check out code
      uses: actions/checkout@main
      with:
        fetch-depth: 0
        token: ${{ secrets.AutoPush }}
    - name: Update README with current date/time
      env:
        GITHUB_TOKEN: ${{ secrets.AutoPush }}
      run: |
        current_date=$(date +"%H:%M %b %d %Y")
        sed -i "s/[0-9]\{2\}:[0-9]\{2\} [A-Z][a-z]\{2\} [0-9]\{2\} [0-9]\{4\}/$current_date/g" README.md
        git config --global user.name 'Auto User'
        git config --global user.email 'auto@users.noreply.github.com'
        git add README.md
    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.AutoPush }}
      run: |
        git commit -am "Automated readme update"
        git push origin HEAD